(function(q){function y(){if(b.ishttps){i.gifpath="https://vstgif.17u.cn/__tctm.gif";i.eventpath="https://vstlog.17u.cn/TrackEvent/TrackEvent.ashx";i.clickpath="https://vstlog.17usoft.com/HeatMap/ClickStream.ashx";i.xpathurl="https://vstlog.17usoft.com/trackless/_trackless.ashx"}}function K(){b.ct=[b.dl.hostname.toLowerCase()==="m.ly.com"?"2":"1",b.ca.split(".")[0],b.ca.split(".")[4],b.cb.split(".")[3],b.cb.split(".")[0],b.uid].join("\u02c7");b.d.cookie="__tctrack=0;path=/;"+b.dc}function L(){b.tpd=
M(b.dm).toLowerCase();b.dc="domain="+b.tpd+";";return B(b.tpd)}function N(){if(!b.dr&&typeof window.opener!="undefined"&&window.opener)try{b.dr=window.opener.location.href}catch(a){}if(b.dr){if(b.dr.indexOf("[")==0&&b.dr.lastIndexOf("]")==b.dr.length-1)b.dr="-"}else b.dr="-";O(b.dr)}function O(a){b.dr=a.replace("http://","").replace("https://","");b.fpd=M(a).toLowerCase()}function M(a){var c=a.match(i.pd);if(c!=null)return c[0];c=0;if((c=a.indexOf("/"))>-1)return a.substring(0,c);return a}function B(a){if(!a)return 1;
for(var c=0,e=0,d=a.length-1;d>=0;d--){e=parseInt(a.charCodeAt(d));c=(c<<6&268435455)+e+(e<<14);if((e=c&266338304)!=0)c^=e>>21}return c}function C(){var a=0,c=0;b.ca=t("__tctma");b.cb=t("__tctmb");var e=t("__tctmu");b.cz=t("__tctmz");if(!i.cazz.test(b.ca)){b.ca=b.u+"."+b.mt+"."+b.mt+"."+b.mt+".1";a=-1}if(!i.cbzz.test(b.cb)){b.cb=b.hid+"."+b.mt+"."+b.mt+".1";c=-1}var d=0,f=B(b.du.toLowerCase()),g=B(b.dr.toLowerCase());if(a==0&&c==0){a=t("__tctmc");c=t("__tctmd");if(a!=f||c!=g){b.cb=P(b.cb);o("__tctmc",
f);o("__tctmd",g)}else d=1}else{if(a==0)b.ca=P(b.ca);o("__tctmc",f);o("__tctmd",g);b.fns=1}Q(e);return d}function P(a){var c=a.split("."),e=c[c.length-1]*1+1,d=c[c.length-2];a="";for(var f=0;f<c.length-3;f++)a+=c[f]+".";a+=d+"."+b.mt+"."+e;return a}function Q(a){if(a=="-"){b.cu=0;b.ci=0}else if(a.indexOf("tckeyword=")>-1){b.cu=a.replace("tckeyword=","");b.ci=0}else{b.cu=a.split(".")[0];b.ci=a.split(".")[1]}}function t(a){a=p(b.d.cookie,a+"="+b.dmh,";");if(a!="-")a=a.substring(a.indexOf(".")+1);return a}
function p(a,c,e){if(!a||!c||!e)return"-";var d,f="-";d=a.indexOf(c);c=c.indexOf("=")+1;if(d>-1){e=a.indexOf(e,d);if(e<0)e=a.length;f=a.substring(d+c,e)}return f}function o(a,c,e){var d="";d=a=="longKey"?a+"="+c+";path=/;":a+"="+b.dmh+"."+c+";path=/;";if(e)d+=e;d+=b.dc;b.d.cookie=d}function D(){if(typeof _tcq!="undefined")for(var a="",c=0;c<_tcq.length;c++)if(typeof _tcq[c][1]!="undefined"){a=_tcq[c][0].toLowerCase().replace(/{|\^|}/g,"");var e=_tcq[c][1];switch(a){case "_serialid":b.orser=e;break;
case "_vrcode":b.acct=e;break;case "_trackpageview":b.pview=e;break;case "_refid":b.refid=e;break;case "_userid":b.uid=e;break;case "_resid":b.resid=e;break;case "_qdid":b.qdid=e;break;case "_flag":b.fg=e}}}function R(){var a="",c="-",e=0,d=0,f=0,g=b.cz;f=b.dls;c=p(f,i.crf+"=","&");try{c!="-"&&c!=""&&O(typeof decodeURIComponent=="function"?decodeURIComponent(c):decodeURI(c))}catch(h){}c=p(f,i.csr+"=","&");if(c!="-"&&c!=""){a="utmcsr="+j(r(c));c=p(f,i.ccn+"=","&");a+=c!="-"&&c!=""?"|utmccn="+j(r(c)):
"|utmccn=(not+set)";c=p(f,i.cmd+"=","&");a+=c!="-"&&c!=""?"|utmcmd="+j(r(c)):"|utmcmd=(not+set)";c=S(1);if(c!="-"&&c!="")a+=c;c=p(f,i.cct+"=","&");if(c!="-"&&c!="")a+="|utmcct="+j(r(c))}if(a=="-"||a=="")a=S();if(a=="-"||a=="")a=ca();c=p(f,i.ctr+"=","&");b.cu=c!="-"&&c!=""?c:b.cu;c=p(f,i.cti+"=","&");b.ci=c!="-"&&c!=""?c:b.ci;if(a=="-"||a==""||typeof a=="undefined"){if(g=="-")a="utmccn=(direct)|utmcsr=(direct)|utmcmd=(none)";if(a=="-"||a=="")return""}if(g!="-"){f=g.indexOf(".");if(f>-1)f=g.indexOf(".",
f+1);if(f>-1)f=g.indexOf(".",f+1);c=g.substring(f+1,g.length);if(c.toLowerCase()==a.toLowerCase())e=1;c=g.substring(0,f);if((f=c.lastIndexOf("."))>-1){c=c.substring(f+1,c.length);d=c*1}}if(e==0||b.fns==1){d++;b.cz=b.mt+"."+b.ca.split(".")[b.ca.split(".").length-1]+"."+d+"."+a}return e==0||b.fns==1?"&utmcn=1":"&utmcr=1"}function ca(){if(b.dr=="0"||b.dr==""||b.dr=="-")return"";var a=b.dr.toLowerCase(),c="-";if(a.indexOf("/")>-1){c=a.substring(a.indexOf("/")+1,a.length);if(c.indexOf("?")>-1)c=c.substring(0,
c.indexOf("?"))}if(!i.ldm.test(b.fpd)&&b.fpd!=b.tpd){b.cu=0;b.ci=0;return"utmccn=(referral)|utmcsr="+r(b.fpd)+"|utmcct="+r(c)+"|utmcmd=referral"}else return""}function S(a){if(b.dr=="0"||b.dr==""||b.dr=="-")return"";for(var c=0,e=b.dr.toLowerCase(),d,f=0;f<i.osr.length;f++)if(b.fpd.indexOf(i.osr[f])>-1)if((c=e.indexOf("?"+i.okw[f]+"="))>-1||(c=e.indexOf("&"+i.okw[f]+"="))>-1){d=e.substring(c+i.okw[f].length+2,e.length).replace("|","\u2016");if((c=d.indexOf("&"))>-1)d=d.substring(0,c);c="-";if(i.esl[f]!=
"")c=p(e.substring(e.indexOf("?")+1,e.length),i.esl[f]+"=","&");if(i.eslutf.test(e))c="utf-8";if(c=="-"){c="utf-8";if(i.eslgb.test(i.osr[f]))c="gb2312";switch(i.osr[f]){case "baidu":if(e.indexOf("ssid=0/from=844b")>0)c="utf-8"}}b.cu=0;b.ci=0;return a?"|utmEsl="+c+"|utmctr="+r(d):"utmccn=(organic)|utmcmd=organic|utmEsl="+c+"|utmcsr="+i.osr[f]+"|utmctr="+r(d)}return""}function r(a){return a.replace(/ /g,"+")}function T(){var a="";a+=j("__tctma="+b.dmh+"."+b.ca+";+");a+=j("__tctmb="+b.dmh+"."+b.cb.substring(b.cb.indexOf(".")+
1,b.cb.length)+";+");a+=j("__tctmu="+b.dmh+".tckeyword="+b.cu+"|tcideaid="+b.ci+";");a+=j("__tctmz="+b.dmh+"."+b.cz+";+");return a}function U(){try{var a="";if(self.screen)a=screen.width+"x"+screen.height;else if(self.java){var c=java.awt.Toolkit.getDefaultToolkit().getScreenSize();a=c.width+"x"+c.height}var e="utmss="+a+";utmsc="+(window.screen.colorDepth+" bit ")+";utmep="+V()+";utmos="+da()+";utmbor="+ea()+";utmfls=";a=0;if(window.ActiveXObject){var d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");
if(d){d.GetVariable("$version").split(" ")[1].replace(/,/g,".").replace(/^(d+.d+).*$/,"$1");a=NaN}}else if(navigator.plugins&&navigator.plugins.length>0)if(d=navigator.plugins["Shockwave Flash"]){var f=d.description.split(" ");d=0;for(var g=f.length;d<g;d++){var h=Number(f[d]);if(!isNaN(h)){a=h;break}}}var k=e+a+";utmjava="+navigator.javaEnabled()+";utmlan=";e="";if(navigator.language)e=navigator.language.toLowerCase();else if(navigator.browserLanguage)e=navigator.browserLanguage.toLowerCase();return k+
e+";utmcoo="+navigator.cookieEnabled}catch(l){return""}}function z(){var a="openid="+E("WxUser=openid","openid")+";unionid="+E("WxUser=openid","unionid");a+=window.__wxjs_environment==="miniprogram"?";env=miniprogram":";env=webview";a+=";wxappscene="+E("WxAppScene=wxappscene","wxappscene");return a}function E(a,c){var e="";try{for(var d=p(b.d.cookie,a,";").split("&"),f=0;f<d.length;f++){var g=d[f].split("="),h=g[1];if(c==g[0])e=h}}catch(k){}return e}function j(a,c){return typeof encodeURIComponent==
"function"?c?encodeURI(a):encodeURIComponent(a):escape(a)}function v(a,c){c+=1;if(!(c>2||!a)){var e=new Image;e.src=a+"&_v="+c+"&dt="+(new Date).getTime();e.onload=function(){delete e};e.onerror=function(){v(a,c);return true}}}function F(a,c,e,d){c+=1;if(c>2||!a)d&&e(false);else{var f=document.createElement("script");f.language="javaScript";f.type="text/JavaScript";f.src=a+"&_v="+c;document.getElementsByTagName("head")[0].appendChild(f);f.onerror=function(){F(a,c,e,d);return true};f.onload=function(){e&&
e()}}}function G(){if(b.fg){b.abtkey=p(b.d.cookie,"abtkey=",";");var a="";a+="&utmn="+Math.round(Math.random()*2147483647);a+=R();if(b.d.title)a+="&utmdt="+j(b.d.title);a+="&utmhid="+b.cb.split(".")[0];a+="&utmr="+j(b.dr);a+="&utmp="+j(b.du);if(b.orser)a+="&serialid="+b.orser;if(b.resid)a+="&resourceid="+b.resid;if(b.abtkey&&b.abtkey!="-")a+="&abtkey="+b.abtkey;if(b.qdid)a+="&qdid="+b.qdid;if(b.pview)a+="&Pageview="+j(b.pview);a+="&refId="+b.refid+"&userId="+b.uid;a=i.gifpath+"?utmac="+b.acct+a+"&utmcc="+
T()+"&bInfo="+j(U())+"&wx="+j(z());v(a,0);b.fns=0;o("__tctmu",b.cu+"."+b.ci,"");b.cz!="-"&&b.cz!=""&&o("__tctmz",b.cz,"")}}function fa(){var a=document.createElement("script");a.type="text/javascript";a.src="http://www."+b.fpd+"/vstjsonp/GetCookie.ashx?CookieKey=__tctma,__tctmu,__tctmz&CallBack=_tcTraObj.CallBack";a.onreadystatechange=a.onerror=function(){if(!this.readyState||(this.readyState==="loaded"||this.readyState==="complete")&&!window[obj])G()};document.getElementsByTagName("head")[0].appendChild(a)}
function da(){try{var a=navigator.userAgent.toLowerCase(),c=navigator.platform=="Win32"||navigator.platform=="Win64"||navigator.platform=="Windows";if(c){if(a.indexOf("windows nt 5.0")>-1||a.indexOf("windows 2000")>-1)return"Win2000";if(a.indexOf("windows nt 5.1")>-1||a.indexOf("Windows XP")>-1)return"WinXP";if(a.indexOf("windows nt 5.2")>-1||a.indexOf("windows 2003")>-1)return"Win2003";if(a.indexOf("windows nt 6.0")>-1||a.indexOf("windows Vista")>-1)return"WinVista";if(a.indexOf("windows nt 6.1")>
-1||a.indexOf("windows 7")>-1)return"Win7";a.indexOf("windows nt 8.0")>-1||a.indexOf("windows 8");if(e)return"Win8";var e=a.indexOf("windows nt 10.0")>-1||a.indexOf("windows 10")>-1;if(e)return"Win10"}var d=navigator.platform=="Mac68K"||navigator.platform=="MacPPC"||navigator.platform=="Macintosh"||navigator.platform=="MacIntel";if(d)return"MacOS";if(a.indexOf("iphone")>-1){var f=a.match(/cpu iphone os (.*?) like mac os/)[1].replace(/_/g,".");return"IOS "+f}if(a.indexOf("ipad")>-1)return"iPad";if(navigator.platform==
"X11"&&!c&&!d)return"Unix";var g=String(navigator.platform).indexOf("Linux")>-1,h=a.toLowerCase().match(/android/i)=="android";if(g)if(h){f=a.substr(a.indexOf("android")+8,a.indexOf(";",a.indexOf("android"))-a.indexOf("android")-8);return"Android "+f}else return"Linux";return"other"}catch(k){return""}}function ea(){try{var a=window.navigator.userAgent.toLowerCase();if(V()){var c=a.indexOf("compatible")>-1&&a.indexOf("msie")>-1,e=a.indexOf("edge")>-1&&!c,d=a.indexOf("trident")>-1&&a.indexOf("rv:11.0")>
-1;if(c){var f=a.toLowerCase().match(/msie ([\d\.])/);if(f.length>0){var g=f[1];return g==7?"ie7\u6d4f\u89c8\u5668":g==8?"ie8\u6d4f\u89c8\u5668":g==9?"ie9\u6d4f\u89c8\u5668":g==10?"ie10\u6d4f\u89c8\u5668":"ie\u6d4f\u89c8\u5668"}else return"ie\u6d4f\u89c8\u5668"}else return e?"edge\u6d4f\u89c8\u5668":d?"IE11\u6d4f\u89c8\u5668":a.indexOf("qqbrowser")>-1||a.indexOf("qq")>-1?"\u817e\u8bafQQ\u6d4f\u89c8\u5668":a.indexOf("safari")>-1&&a.indexOf("metasr")>-1?"\u641c\u72d7\u6d4f\u89c8\u5668":a.indexOf("bidubrowser")>
-1?"\u767e\u5ea6\u6d4f\u89c8\u5668":a.indexOf("lbbrowser")>-1?"\u730e\u8c79\u6d4f\u89c8\u5668":a.indexOf("firefox")>-1?"\u706b\u72d0\u6d4f\u89c8\u5668":a.indexOf("maxthon")>-1?"\u9068\u6e38\u6d4f\u89c8\u5668":a.indexOf("opera")>-1?"\u6b27\u670b\u6d4f\u89c8\u5668":a.indexOf("theworld")>-1?a="\u4e16\u754c\u4e4b\u7a97\u6d4f\u89c8\u5668":a.indexOf("ubrowser")>-1?"UC\u6d4f\u89c8\u5668":a.indexOf("safari")>-1&&a.indexOf("chrome")==-1?"safari\u6d4f\u89c8\u5668":a.indexOf("chrome")>-1?"\u8c37\u6b4c\u6d4f\u89c8\u5668":
"\u5176\u4ed6PC\u6d4f\u89c8\u5668"}else return a.indexOf("mqqbrowser")>-1?"\u624b\u673aQQ\u6d4f\u89c8\u5668":a.indexOf("baidubrowser")>-1?"\u624b\u673a\u767e\u5ea6\u6d4f\u89c8\u5668":a.indexOf("fxios")>-1||a.indexOf("firefox")>-1?"\u624b\u673a\u706b\u72d0\u6d4f\u89c8\u5668":a.indexOf("micromessenger")>-1?"\u5fae\u4fe1\u6d4f\u89c8\u5668":a.indexOf("ucbrowser")>-1?"uc\u624b\u673a\u6d4f\u89c8\u5668":a.indexOf("liebaofast")>-1?"\u730e\u8c79\u624b\u673a\u6d4f\u89c8\u5668":a.indexOf("qihoobrowser")>-1?
"360\u624b\u673a\u6d4f\u89c8\u5668":a.indexOf("sogoumobilebrowser")>-1?"\u641c\u72d7\u624b\u673a\u6d4f\u89c8\u5668":a.indexOf("crios")>-1||a.indexOf("chrome")>-1?"\u8c37\u6b4c\u79fb\u52a8\u7248\u6d4f\u89c8\u5668":a.indexOf("safari")>-1&&a.indexOf("chrome")==-1?"safari\u79fb\u52a8\u7248\u6d4f\u89c8\u5668":" webkit browser"}catch(h){return""}}function V(){for(var a=navigator.userAgent,c=["Android","iPhone","SymbianOS","Windows Phone","iPad","iPod"],e=true,d=0;d<c.length;d++)if(a.indexOf(c[d])>0){e=
false;break}return e}var b={dc:"",d:q,dl:q.location,dls:q.location.search,dm:q.domain,dmh:0,du:q.location.href.replace("http://","").replace("https://",""),dr:q.referrer,ishttps:q.location.protocol=="https:",fpd:"",tpd:"",u:_tclk,mt:_tcmmt,dt:(new Date).getTime(),fns:0,acct:"-",orser:"",pview:"",refid:0,uid:0,resid:0,qdid:0,abtkey:"",fg:true,ca:"",cb:"",cu:"",ci:"",cz:"",ct:"",hid:Math.round(Math.random()*4503599627370495)},i={ccn:"utm_campaign",cct:"utm_content",cmd:"utm_medium",csr:"utm_source",
crf:"utm_referrer",ctr:"tcbdkeyid",cti:"tcideaid",osr:["baidu","baidu","google","sogou","soso","youdao","bing","yahoo","114so","gougou","jike","panguso","360","so","sogou"],okw:["wd","word","q","query","w","q","q","p","kw","search","q","q","q","q","keyword"],esl:["ie","ie","ie","ie","ie","ue","","ei","","","","","ie","ie",""],eslutf:/(m.baidu.com|wap.baidu.com|baidu.mobi|3g.baidu.com|m1.baidu.com|m5.baidu.com)/,eslgb:/^(baidu|soso|sogou|118114)$/,ta:/^(172.|192.|127.|10.|localhost)/,ldm:/(ly.com|tongcheng.com|17u.cn|17u.com|17u.net)/,
pd:/[\w-]+\.(com|net|org|gov|cc|biz|info|cn|mil|biz|name|rec)(\.(cn|hk|ca|pe))*/,cazz:/^(\d+\.\d+\.\d+\.\d+\.\d+){1}$/,cbzz:/^(\d+\.\d+\.\d+\.\d+){1}$/,gifpath:"http://vstgif.17usoft.com/__tctm.gif",eventpath:"http://vstlog.17usoft.com/TrackEvent/TrackEvent.ashx",clickpath:"http://vstlog.17usoft.com/HeatMap/ClickStream.ashx",xpathurl:"http://vstlog.17usoft.com/trackless/_trackless.ashx"};(function(){D();if(b.fg)if(b.dl.protocol!="file:")if(!i.ta.test(b.dm)){y();b.dmh=L();if(b.dmh>0){N();if(!b.dls)b.dls=
"";if(typeof b.dl.hash!="undefined"&&b.dl.hash)b.dls=b.dls.replace("?","")+b.dl.hash.replace("#","&");var a,c;c="expires="+(new Date(b.dt+63072E6)).toGMTString()+";";a="expires="+(new Date(b.dt+18E5)).toGMTString()+";";var e=C();o("__tctma",b.ca,c);o("__tctmb",b.cb,a);if(e==0)!b.ishttps&&b.fpd!=b.tpd&&i.ldm.test(b.fpd)?fa():G()}o("longKey",b.ca.split(".")[0],"");K()}})();window._tcTraObj={CallBack:function(a){try{if(a){var c=eval(a);c.hasOwnProperty("__tctmu")&&c.__tctmu.length>0&&Q(c.__tctmu.substr(c.__tctmu.indexOf(".")+
1));if(c.hasOwnProperty("__tctmz")&&c.__tctmz.length>0){var e=c.__tctmz.indexOf(".");if(e>-1)e=c.__tctmz.indexOf(".",e+1);if(e>-1)e=c.__tctmz.indexOf(".",e+1);if(e>-1)e=c.__tctmz.indexOf(".",e+1);var d=c.__tctmz.substring(e+1,c.__tctmz.length);if(b.cz=="-")d=b.mt+"."+b.ca.split(".")[b.ca.split(".").length-1]+".1."+d;else{e=b.cz.indexOf(".");a=0;if(e>-1)e=b.cz.indexOf(".",e+1);if(e>-1)e=b.cz.indexOf(".",e+1);var f=b.cz.substring(0,e);if((e=f.lastIndexOf("."))>-1){f=f.substring(e+1,f.length);a=f*1}d=
b.mt+"."+b.ca.split(".")[b.ca.split(".").length-1]+"."+a+"."+d}b.cz=d}}}catch(g){}G()},_tcTrackEvent:function(a,c,e,d,f){if(a&&c){D();var g="{";if(!f)f=b.du;g+='"LoginKey":'+b.ca.split(".")[0];g+=',"LoginCount":'+b.ca.split(".")[4];g+=',"SessionId":'+b.cb.split(".")[0];g+=',"PageCount":'+b.cb.split(".")[3];g+=',"Category":"'+j(a)+'"';g+=',"Action":"'+j(c)+'"';g+=',"FromPage":"'+j(f)+'"';g+=',"Label":"'+(e?j(e):"")+'"';g+=',"Value":"'+(d?j(d):"")+'"';g+=',"PageView":"'+j(b.pview)+'"';g+=',"DesVRCode":"'+
b.acct+'"';g+=',"Wx":"'+j(z())+'"';g+="}";v(i.eventpath+"?TrackEvent="+g,0)}},CookieInfo:function(){return b.ct},_tcTrackPage:function(a,c){b.du=b.dm+"/sg/"+a;b.dr=b.dm+"/sg/"+c;D();if(!b.fg)if(b.dl.protocol!="file:")if(!i.ta.test(b.dm)){y();b.dmh=L();if(b.dmh>0){N();if(!b.dls)b.dls="";if(typeof b.dl.hash!="undefined"&&b.dl.hash)b.dls=b.dls.replace("?","")+b.dl.hash.replace("#","&");var e,d;d="expires="+(new Date(b.dt+63072E6)).toGMTString()+";";e="expires="+(new Date(b.dt+18E5)).toGMTString()+";";
var f=C();o("__tctma",b.ca,d);o("__tctmb",b.cb,e);if(f==0)if(!b.fg){b.abtkey=p(b.d.cookie,"abtkey=",";");e="";e+="&utmn="+Math.round(Math.random()*2147483647);e+=R();if(b.d.title)e+="&utmdt="+j(b.d.title);e+="&utmhid="+b.cb.split(".")[0];e+="&utmr="+j(b.dr);e+="&utmp="+j(b.du);if(b.orser)e+="&serialid="+b.orser;if(b.pview)e+="&Pageview="+j(b.pview);if(b.resid)e+="&resourceid="+b.resid;if(b.abtkey&&b.abtkey!="-")e+="&abtkey="+b.abtkey;if(b.qdid)e+="&qdid="+b.qdid;e+="&refId="+b.refid+"&userId="+b.uid;
e=i.gifpath+"?utmac="+b.acct+e+"&utmcc="+T()+"&bInfo="+j(U())+"&wx="+j(z());v(e,0);b.fns=0;o("__tctmu",b.cu+"."+b.ci,"");b.cz!="-"&&b.cz!=""&&o("__tctmz",b.cz,"")}}o("longKey",b.ca.split(".")[0],"");K()}},_tcRequestJs:F};(function(a){var c,e=function(g){if(!_tcHotmapx.pid||parseInt(Math.random()*100)>_tcHotmapx.sp)return false;flag=false;c&&clearTimeout(c);c=setTimeout(function(){flag=true},500);g=d(g);return"?rx="+(g.x-parseInt(f()/2,10))+"&ry="+g.y+"&pid="+_tcHotmapx.pid},d=function(g){g=g||window.event;
return{x:g.pageX||g.clientX+(document.documentElement.scrollLeft||document.body.scrollLeft),y:g.pageY||g.clientY+(document.documentElement.scrollTop||document.body.scrollTop)}},f=function(){var g,h;if(window.innerWidth&&window.scrollMaxX)g=window.innerWidth+window.scrollMaxX;else if(document.body.scrollHeight>document.body.offsetHeight)g=document.body.scrollWidth;else if(document.body)g=document.body.offsetWidth;if(window.innerWidth)h=window.innerWidth;else if(document.documentElement&&document.documentElement.clientWidth)h=
document.documentElement.clientWidth;else if(document.body)h=document.body.clientWidth;return g<h?h:g};typeof _tcHotmapx=="undefined"||!_tcHotmapx||function(g,h,k){if(g.addEventListener)g.addEventListener(h,k,false);else g.attachEvent&&g.attachEvent("on"+h,k)}(a,"mousedown",function(g){if(e(g)){y();g=i.clickpath+e(g);F(g,0)}})})(q);var ga=function(){return new function(){_keyStr="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";this.encode=function(a){var c="",e,d,f,g,h,k,l=0;for(a=
_utf8_encode(a);l<a.length;){e=a.charCodeAt(l++);d=a.charCodeAt(l++);f=a.charCodeAt(l++);g=e>>2;e=(e&3)<<4|d>>4;h=(d&15)<<2|f>>6;k=f&63;if(isNaN(d))h=k=64;else if(isNaN(f))k=64;c=c+_keyStr.charAt(g)+_keyStr.charAt(e)+_keyStr.charAt(h)+_keyStr.charAt(k)}return c};this.decode=function(a){var c="",e,d,f,g,h,k=0;for(a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");k<a.length;){e=_keyStr.indexOf(a.charAt(k++));d=_keyStr.indexOf(a.charAt(k++));g=_keyStr.indexOf(a.charAt(k++));h=_keyStr.indexOf(a.charAt(k++));e=e<<
2|d>>4;d=(d&15)<<4|g>>2;f=(g&3)<<6|h;c+=String.fromCharCode(e);if(g!=64)c+=String.fromCharCode(d);if(h!=64)c+=String.fromCharCode(f)}return c=_utf8_decode(c)};_utf8_encode=function(a){a=a.replace(/\r\n/g,"\n");for(var c="",e=0;e<a.length;e++){var d=a.charCodeAt(e);if(d<128)c+=String.fromCharCode(d);else{if(d>127&&d<2048)c+=String.fromCharCode(d>>6|192);else{c+=String.fromCharCode(d>>12|224);c+=String.fromCharCode(d>>6&63|128)}c+=String.fromCharCode(d&63|128)}}return c};_utf8_decode=function(a){for(var c=
"",e=0,d=c1=c2=0;e<a.length;){d=a.charCodeAt(e);if(d<128){c+=String.fromCharCode(d);e++}else if(d>191&&d<224){c2=a.charCodeAt(e+1);c+=String.fromCharCode((d&31)<<6|c2&63);e+=2}else{c2=a.charCodeAt(e+1);c3=a.charCodeAt(e+2);c+=String.fromCharCode((d&15)<<12|(c2&63)<<6|c3&63);e+=3}}return c}}}();window._TCTRACK_CLICKCHOOSE_STATUS=window._TCTRACK_CLICKCHOOSE_STATUS||false;try{var H,W,X=function(a){if(H){try{a.list[0].locationHref=b.du}catch(c){}H.postMessage(a,"*")}};window.TCTRACK_sendMessageToQxPage=
X;window.addEventListener("message",function(a){var c=a.data;H=a.source;if(!W){W=true;a.source.postMessage({connect:true},"*")}c&&c.eventTypes=="tcqx"&&ha(c)},false);var ha=function(a){var c=a.eventName;switch(c){case "loadJs":a=a.list;a.push(function(e,d){X({eventName:"loadJs",isLoadQXJs:d,list:[{success:e===false?0:1,isLoadQXJs:d}]})});if(window._TC_TRACK_CIRCLE_SELECT_SERVICE){a[a.length-1](true,true);break}_tcTraObj._tcRequestJs.apply(this,a);break;default:window._TC_TRACK_CIRCLE_SELECT_SERVICE[c].apply(this,
a.list)}};window.top.postMessage({connect:true,isLoad:false,location:b.du},"*")}catch(ka){}(function(){function a(d){if(document.documentElement==d||d==document.body||!d)return{top:0,left:0};d=d.getBoundingClientRect();var f=d.top-document.documentElement.clientTop+document.documentElement.scrollTop,g=d.bottom,h=d.left-document.documentElement.clientLeft+document.documentElement.scrollLeft,k=d.right;return{t:f,r:k,b:g,l:h,w:d.width||k-h,h:d.height||g-f}}function c(d){var f=d.tagName.toLowerCase(),
g=d.parentNode;if(f=="body"||f=="html")return[[d],0];if(g.nodeType==1)for(var h=[],k=-1,l=0;l<g.childNodes.length;l++){var n=g.childNodes[l];if(n.nodeType==1&&f==n.tagName.toLowerCase()){h.push(n);if(n==d)k=h.length-1}}return[h,k]}y();(function(d,f,g){if(d.addEventListener)d.addEventListener(f,g,false);else d.attachEvent&&d.attachEvent("on"+f,g)})(q,"click",function(d){if(!_TCTRACK_CLICKCHOOSE_STATUS)try{var f=e,g;var h=d.target;if(!(document.documentElement==h||h==document.body))for(var k=true;k;){var l=
a(h),n=a(h.parentNode);if(l.t==n.t&&l.l==n.l&&l.w==n.w&&l.h==n.h)h=h.parentNode;else k=false}g=f(h).xpath;var m=d.target;d="";var Y=m.getAttribute("href"),w=m.getAttribute("alt"),ia=m.getAttribute("title");d+="&pageurl="+j(b.du);d+="&loginkey="+b.u;d+="&sessionid="+b.hid;b.cz||C();var s=b.cz&&b.cz.split(".")[2];d+=s?"&logincount="+s:"";s="";try{switch(m.tagName.toLowerCase()){case "img":s="&descr="+j(w);break;case "a":s="&descr="+j(ia)}}catch(la){}d+=s;if(!s){var A;w="";var x=m.nodeType;if(x===3||
x===4)A=m.nodeValue;else{if(x===1||x===9||x===11){var I=m.childNodes;if(I.length==0)w=m.innerHTML||m.value;else for(m=0;m<I.length;m++){var Z=I.item(m),$=Z.nodeType;if($==3||$==4)w+=Z.nodeValue}}A=w}var J;J=A?(A+"").replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,""):"";d+=J?"&descr="+j(J):""}var aa=b.acct.split("-"),ba=b.pview.split("||");d+=Y?"&linkto="+j(Y):"";d+="&platcode="+aa[0];d+="&productcode="+aa[1];d+="&memberid="+b.uid;try{var u=g.split("/");u=u[u.length-1];u=u.match(/\d+/g)[0];d+="&position="+
u}catch(ma){}d+=ba.length>1?"&openid="+j(ba[0]):"";d+="&wx="+j(z());var ja=i.xpathurl+"?elepath="+ga.encode(g)+d;v(ja,0)}catch(na){}});var e=function(d,f){for(var g=f||[],h={xpath:"",css:""},k={isUniqueId:function(n,m){return!!(m&&m.indexOf(n)==-1)},getClass:function(n){var m="";n=n.className;if(typeof n!="undefined"&&n!="")m="."+n.split(/[\s\n]+/).join(".");return m}};d&&d.nodeType==1;d=d.parentNode){var l=c(d)[1]+1;if(d.tagName.substring(0,1)!="/")if(d.id!="undefined"&&d.id!=""&&k.isUniqueId(d.id,
g)){g.push(d.id);l="[@id='"+d.id+"']";h.xpath="/"+d.tagName.toLowerCase()+l+h.xpath;h.css=d.tagName.toLowerCase()+"#"+d.id+" > "+h.css}else{l="["+l+"]";h.xpath="/"+d.tagName.toLowerCase()+l+h.xpath;h.css=d.tagName.toLowerCase()+k.getClass(d)+" > "+h.css}}h.xpath="/"+h.xpath;h.css=h.css.substr(0,h.css.length-3);return h}})()})(document||window.document);
